### SpringCloud注册中心EurekaServer集群部署 - peer1服务器

server:
  port: 8761

spring:
  application:
    name: spring-cloud-eureka-server #指定服务名称

eureka:
  instance:
    hostname: localhost #指定主机地址（集群部署，该注册中心部署在peer1服务器）
  client:
    fetch-registry: true #指定是否要从注册中心获取服务（因为是集群模式，该注册中心服务对于其他服务器的注册中心来说是一个客户端）
    register-with-eureka: true #指定是否要注册到注册中心（因为是集群模式，该注册中心服务对于其他服务器的注册中心来说是一个客户端）
  service-url:
    defaultZone: http://peer2:8761/eureka/,http://peer3:8761/eureka/ # 配置注册中心地址（分别为peer2、peer3服务器的注册中心地址）